---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echoserver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: echoserver
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/chrisalbright/argocd-apps.git
    targetRevision: HEAD
    path: echoserver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
      limit: 10
    syncOptions:
      - Validate=false
        CreateNamespace=true
        PrunePropagationPolicy=foreground
        PruneLast=true
        RespectIgnoreDifferences=true

